env:
  es2021: true
  node: true
extends: eslint:recommended
plugins:
  - prettier
  - import
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  # possible errors
  no-unused-vars: warn
  # plugins
  prettier/prettier: error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
        - unknown
