# =============================================================================
# ConfigFile: config/constants.yml
# Description: 一些常量的配置文件
# Since: 2.4.0
# =============================================================================

# -----------------------------------------------------------------------------
# Amber.top 配置
# version: API版本
# site: https://gi.yatta.moe/
# -----------------------------------------------------------------------------
amber:
  version: 58F0
  api: https://gi.yatta.moe/api/v2/
  site: https://gi.yatta.moe/
  assets: https://gi.yatta.moe/assets/UI/
