# =============================================================================
# ConfigFile: config/material.yml
# Description: 材料的配置文件
# Since: 2.0.0
# =============================================================================

# -----------------------------------------------------------------------------
# 额外添加的材料
# -----------------------------------------------------------------------------
material:
  - 105 # 好感
  - 201 # 原石
  - 210 # 树脂
